DEFAULT_REQUIRED_PPE = ("helmet", "vest")
DEFAULT_TRACK_STABLE_HITS = 3
DEFAULT_MISSING_PERSISTENCE_SECONDS = 3.0
DEFAULT_MIN_VALID_INFERENCES = 4
DEFAULT_PREVIEW_FPS = 10
DEFAULT_INFERENCE_FPS = 3
DEFAULT_FRAME_QUEUE_SIZE = 2
DEFAULT_RING_BUFFER_SECONDS = 2
